env:
  global:
    - MAKEFLAGS="-j 8"
language: cpp
dist: focal
os: linux
arch: amd64

jobs:
  include:
    - name: GCC 7 Test
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - libgsl-dev
            - libncurses5-dev
            - python3
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
        - BUILD_OPTIONS="-DPAASS_BUILD_TESTS=ON -DPAASS_BUILD_UTKSCAN=ON -DPAASS_BUILD_ROOT_SCANNER=OFF -DPAASS_BUILD_SETUP=ON"
    - name: GCC 8 Test
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
            - libgsl-dev
            - libncurses5-dev
            - python3
      env:
        - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"
        - BUILD_OPTIONS="-DPAASS_BUILD_TESTS=ON -DPAASS_BUILD_UTKSCAN=ON -DPAASS_BUILD_ROOT_SCANNER=OFF -DPAASS_BUILD_SETUP=ON"
    - name: GCC 9 Test
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - libgsl-dev
            - libncurses5-dev
            - python3
      env:
        - MATRIX_EVAL=""
        - BUILD_OPTIONS="-DPAASS_BUILD_TESTS=ON -DPAASS_BUILD_UTKSCAN=ON -DPAASS_BUILD_ROOT_SCANNER=OFF -DPAASS_BUILD_SETUP=ON"


before_install:
  - sudo apt-get -qq update --install-suggests
  - eval "${MATRIX_EVAL}"
  - export ORIG_DIR=$PWD
  - git clone https://github.com/unittest-cpp/unittest-cpp.git && cd unittest-cpp/builds/
  - cmake ../ && sudo make install && cd $ORIG_DIR
  - mkdir -p /opt/plx/ && cd /opt/plx
  - git clone https://github.com/spaulaus/plx-api.git && ln -s plx-api current && cd plx-api
  - export PLX_SDK_DIR=$PWD && make all && cd ${ORIG_DIR}
  - git clone https://github.com/spaulaus/xia-api.git && cd xia-api
  - python3 waf configure build install --prefix=${ORIG_DIR} && cd $ORIG_DIR
  - export XIA_ROOT_DIR=${ORIG_DIR}/xia
  - wget https://root.cern/download/root_v6.22.02.Linux-ubuntu20-x86_64-gcc9.3.tar.gz
  - tar xzf root_v6.22.02.Linux-ubuntu20-x86_64-gcc9.3.tar.gz
  - source root/bin/thisroot.sh

script:
  - mkdir paass-build && cd paass-build
  - cmake ../ ${BUILD_OPTIONS} && make -j8 && ctest -j8
